version: '3.6'

services:
  control:
    build: ./control
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - type: bind
        source: ./ansible
        target: /var/ansible

  lb01:
    build: ./base
    stdin_open: true
    tty: true
    restart: always

  app01:
    build: ./base
    stdin_open: true
    tty: true
    restart: always
    hostname: app01

  app02:
    build: ./base
    stdin_open: true
    tty: true
    restart: always
    hostname: app02

  db01:
    build: ./base
    stdin_open: true
    tty: true
    restart: always
