---
- name: install tools
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - mysql-server
    - net-tools
    - python-mysqldb
    - iproute2

- name: ensure mysql listening on all ports
  lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp=^bind-address
              line="bind-address = 0.0.0.0"
  notify: restart mysql

- name: ensure mysql started
  shell: service mysql start

- name: create demo database
  mysql_db: name=demo state=present

- name: create demo user
  mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present
